C		PROGRAM AOFTRI
		REAL A,B,C,AREA
		WRITE(*,*)'ENTER SIDES OF A TRIANGLE'
		READ *,A,B,C
		AREA = AREAOFTRAINGLE(A,B,C)
		WRITE(*,*)'AREA:',AREA
		END

		REAL FUNCTION AREAOFTRAINGLE(X,Y,Z)
		REAL X,Y,Z,S
		S = (X+Y+Z)/2.0
		AREAOFTRAINGLE = SQRT(S*(S-X)*(S-Y)*(S-Z))
		RETURN
		END