C		FIND THIRD SIDE OF RT. TRIANGLE
C		PERPENDICULAR & BASE
		PROGRAM ABC
		REAL P,B,H
		WRITE(*,*)'ENTER P AND B:'
		READ *,P,B
		CALL CALCCHYP(P,B,H)
		WRITE(*,*)'H:',H
		END

		SUBROUTINE CALCCHYP(X,Y,OUTPUT)
		REAL X,Y,OUTPUT
		OUTPUT = SQRT(X**2 + Y**2)
		RETURN
		END